FROM plexinc/pms-docker:latest

EXPOSE 9229

RUN apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install nodejs -y

WORKDIR /usr/src/plex-transcode-interceptor

COPY package*.json ./
COPY tsconfig*.json ./
COPY ./src src
COPY ./scripts scripts

RUN npm install
RUN npm run build

RUN \
# Replace the transcoder
    cp -f -p ./scripts/debug.sh /usr/lib/plexmediaserver/Plex\ Transcoder